### PR TITLE
fix: recognize panic as terminating statement in missing return check

### LINKED ISSUE #555: Consider recognizing panic() as terminating in missing return detection
## Summary

The new missing return detection feature in gogen v1.19.7 (PR #550) does not recognize `panic()` as a terminating statement, which differs from Go's standard compiler behavior. This requires adding unreachable return statements after panic() calls.

## Current Behavior

**gogen v1.19.7:**
```go
func example() int {
    panic("error")
    // Error: missing return
}
```

Requires adding unreachable return:
```go
func example() int {
    panic("error")
    return 0  // unreachable but required
}
```

**Go standard compiler:**
```go
func example() int {
    panic("error")
    // ✅ Compiles successfully - no error
}
```

## Root Cause

gogen uses `go/types.(*Checker).isTerminating()` via linkname (func.go:136):

```go
if t.Results().Len() > 0 && !goTypesCheckerIsTerminating(checker, body, "") {
    cb.handleCodeError(pos, end, "missing return")
}

//go:linkname goTypesCheckerIsTerminating go/types.(*Checker).isTerminating
func goTypesCheckerIsTerminating(check *types.Checker, s ast.Stmt, label string) bool
```

This function performs static control flow analysis and does not recognize `panic()` as terminating because:
1. `panic()` is a regular function call, not a language construct
2. The type checker's `isTerminating()` is more conservative than the compiler's termination analysis
3. Go's compiler (`cmd/compile`) has special knowledge of `panic()` that `go/types` doesn't have

## Impact

This affects XGo code in goplus/xgo#2515:
- Demo files: `demo/tpl-calc/calc.xgo`, `demo/xgo-calc/calc.xgo`
- Required adding unreachable returns after panic() calls
- Creates inconsistency with standard Go behavior

### Option A: Enhance termination check to recognize panic-like functions
**Pros:**
- Matches Go compiler behavior
- More user-friendly
- No unreachable code needed

**Cons:**
- Requires maintaining list of terminating functions (panic, os.Exit, log.Fatal, etc.)
- Edge cases: shadowed panic, custom panic-like functions
- Diverges from go/types behavior

### Option B: Keep current behavior but document clearly
**Pros:**
- Simple implementation
- Conservative approach
- Consistent with go/types

**Cons:**
- Requires unreachable returns after panic()
- Different from Go compiler

### Option C: Make it configurable
**Pros:**
- Flexibility for different use cases
- Can satisfy both preferences

**Cons:**
- Added complexity
- Configuration burden

## Recommendation

I recommend **Option A** with a carefully curated list of known terminating functions:
- `panic()`
- `os.Exit()`
- `log.Fatal()`, `log.Fatalf()`, `log.Fatalln()`
- `log.Panic()`, `log.Panicf()`, `log.Panicln()`

This would match Go compiler behavior while being practical. Shadowing detection could be added to handle edge cases.

## Related

- gogen PR #550 (missing return detection)
- XGo PR goplus/xgo#2515 (adaptations for gogen v1.19.7)

---

Reported via goplus/xgo#2515 (comment)

### PR DESCRIPTION
**Pull request by aofei**
Reimplement `isTerminating` based on the approach from PR #550 (commit 2938d96), which ports the logic from go/types/return.go in the Go standard library.

The previous implementation used go:linkname to call the internal `go/types.(*Checker).isTerminating`, but this had issues:
- The checker's internal `isPanic` map is empty for newly created checkers, so it cannot recognize panic calls
- A secondary `terminatesWithPanic` check was needed, adding complexity

The new implementation:
- Introduces `termChecker` struct for termination statement analysis
- Tracks builtin panic calls during code generation to correctly handle shadowed panic
- Organizes terminating statement logic in dedicated `return.go` file
- Includes comprehensive unit tests in `return_test.go`

Fixes #555

### CODE REVIEW

**Review by visualfc — APPROVED** [review]

File: package.go [hunk 1]
```diff
@@ -338,6 +338,7 @@ type Package struct {
 	utBigFlt       *types.Named
 	commentedStmts map[ast.Stmt]*ast.CommentGroup
 	implicitCast   func(pkg *Package, V, T types.Type, pv *Element) bool
+	panicCalls     map[*ast.CallExpr]bool // tracks calls to builtin panic
```
Comment (xushiwei) [inline package.go]: This is not package status data and should not be saved here. Add it to type `funcBodyCtx`

Comment (aofei) [reply package.go]: done https://github.com/goplus/gogen/pull/556/changes
